GET http://localhost:8083/testa?id=3

GET http://localhost:8083/testa/list

POST http://localhost:8083/testa HTTP/1.1
content-type: application/json

{
    "key": "{{$guid}}",
    "value": "{{$guid}}"
}